# Generated by Django 4.1.4 on 2022-12-27 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='description',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='video',
        ),
    ]
