# Generated by Django 4.1.4 on 2022-12-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_flower_description_remove_flower_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
